USE sp;

CREATE TABLE IF NOT EXISTS users( 
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  login VARCHAR(20) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  first_name VARCHAR(100),
  last_name VARCHAR(100),
  role_id INT UNSIGNED NOT NULL,
  company_id INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE roles(
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  role_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE companies(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  web_site VARCHAR(120),
  company_name VARCHAR(120),
  hq_address VARCHAR(255),
  industry_id INT UNSIGNED NOT NULL,
  company_type_id INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE industries(
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  industry_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE company_types(
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  company_type_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE products(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  product_name VARCHAR(120) NOT NULL UNIQUE,
  product_description TEXT,
  product_owner INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dev_teams(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  team_name VARCHAR(120) NOT NULL UNIQUE,
  team_leader_name INT UNSIGNED NOT NULL,
  team_specializaton TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE user_processes(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  process_name VARCHAR(120) NOT NULL,
  company_id INT UNSIGNED NOT NULL,
  process_description JSON,
  created_by INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE ideas(
  id SERIAL PRIMARY KEY, 
  idea_name VARCHAR(120) NOT NULL,
  idea_description TEXT,
  idea_details JSON,
  created_by INT UNSIGNED NOT NULL,
  customer_idea BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE feature_requests(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  fr_name VARCHAR(120) NOT NULL,
  idea_id BIGINT UNSIGNED NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  process_id INT UNSIGNED NOT NULL,
  fr_status INT UNSIGNED,
  created_by INT UNSIGNED NOT NULL,
  updated_by INT UNSIGNED,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fr_statuses(
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  status_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE features_commits(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  fc_name VARCHAR(120) NOT NULL,
  fr_id INT UNSIGNED NOT NULL,
  fc_status INT UNSIGNED NOT NULL,
  team_id INT UNSIGNED NOT NULL,
  company_id INT UNSIGNED NOT NULL,
  created_by INT UNSIGNED NOT NULL,
  updated_by INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE fc_statuses(
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  status_name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE messages(
  id SERIAL PRIMARY KEY,
  from_user_id INT UNSIGNED NOT NULL,
  body TEXT NOT NULL,
  idea_id BIGINT UNSIGNED NOT NULL
);

CREATE TABLE roadmaps(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, 
  rm_name VARCHAR(120) NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  start_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  finish_date DATETIME DEFAULT CURRENT_TIMESTAMP
 );

CREATE TABLE roadmaps_features(
  fc_id INT UNSIGNED NOT NULL,
  rm_id INT UNSIGNED NOT NULL,
  PRIMARY KEY (fc_id, rm_id)
);



